---
title: "Executive Summary"
author: "Amirhossein Moghaddas Jafari"
date: "8/16/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary

Netflix, one of the largest technology companies in the media, has been identified some of its users experience choice overload and therefore resulting in a psychological phenomenon known as Decision Paralysis. Their goal was to reduce the time spent browsing to overcome this problem. There is  a suggestion system embedded in Netflix webpage, and their interest lies in designing the system to result in shortest browsing time for the Netflix users.\
There were four factors selected to be explored in this project among many things that likely influence the amount of time someone spends browsing Netflix , and, in order to investigate the problem statistically, an Experimental Design method was used to determine the optimal levels of these factors to obtain the shortest browsing time.\ Four phases have been involved in the Experimental Design. In Phase I, we identified the statistically influential factors, in Phase II, we identified the path toward the optimum and located the location closest to it, and in Phase III, we calculated the optimum point analytically with RSM. Finally, a confirmation experiment method was conducted in Phase IV, to ensure that the estimated optimum would be sustainable.\
The optimum location of the factors has been identified to be 70 Seconds and 78 Percent for Preview Length and Match Score respectively. We also identified the Preview Type of Teaser/Trailer would result in shorter Browsing Time than Actual Content. Tile Size, however, was not a significant factor, set to 0.2 the same as default level.\
For 100 randomly selected users in this configuration, the average browsing time was 10.72 minutes and the commensurate probability obtained from Phase IV suggests that with the probability of 53 Percent, the observations will not exceed 11 minutes.
